<?xml version="1.0" encoding="utf-8"?><Database Name="openXDA" Class="FaultLocationInfoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost\SQLEXPRESS;Initial Catalog=openXDA;Integrated Security=True" SettingsObjectName="FaultData.Properties.Settings" SettingsPropertyName="openXDAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.SegmentType" Member="SegmentTypes">
    <Type Name="SegmentType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="SegmentType_FaultSegment" Member="FaultSegments" ThisKey="ID" OtherKey="SegmentTypeID" Type="FaultSegment" />
    </Type>
  </Table>
  <Table Name="dbo.FaultSegment" Member="FaultSegments">
    <Type Name="FaultSegment">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SegmentTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime2 NOT NULL" CanBeNull="false" />
      <Column Name="StartSample" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EndSample" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="SegmentType_FaultSegment" Member="SegmentType" ThisKey="SegmentTypeID" OtherKey="ID" Type="SegmentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LineImpedance" Member="LineImpedances">
    <Type Name="LineImpedance">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="R0" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="X0" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="R1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="X1" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SourceImpedance" Member="SourceImpedances">
    <Type Name="SourceImpedance">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeterLocationLineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RSrc" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="XSrc" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OutputChannel" Member="OutputChannels">
    <Type Name="OutputChannel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SeriesID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ChannelKey" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LoadOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FaultLocationAlgorithm" Member="FaultLocationAlgorithms">
    <Type Name="FaultLocationAlgorithm">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssemblyName" Type="System.String" DbType="VarChar(1024) NOT NULL" CanBeNull="false" />
      <Column Name="TypeName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="MethodName" Type="System.String" DbType="VarChar(80) NOT NULL" CanBeNull="false" />
      <Column Name="ExecutionOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.FaultEmailTemplate" Member="FaultEmailTemplates">
    <Type Name="FaultEmailTemplate">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Template" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="FaultEmailTemplate_FaultEmailRecipient" Member="FaultEmailRecipients" ThisKey="ID" OtherKey="FaultEmailTemplateID" Type="FaultEmailRecipient" />
    </Type>
  </Table>
  <Table Name="dbo.FaultEmailRecipient" Member="FaultEmailRecipients">
    <Type Name="FaultEmailRecipient">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipientID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FaultEmailTemplateID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeterGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="FaultEmailTemplate_FaultEmailRecipient" Member="FaultEmailTemplate" ThisKey="FaultEmailTemplateID" OtherKey="ID" Type="FaultEmailTemplate" IsForeignKey="true" />
    </Type>
  </Table>
</Database>