<?xml version="1.0" encoding="utf-8"?><Database Name="openXDA" Class="MeterInfoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=openXDA;Integrated Security=True" SettingsObjectName="FaultData.Properties.Settings" SettingsPropertyName="openXDAConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MeterLocation" Member="MeterLocations">
    <Type Name="MeterLocation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssetKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="MeterLocation_MeterLocationLine" Member="MeterLocationLines" ThisKey="ID" OtherKey="MeterLocationID" Type="MeterLocationLine" />
      <Association Name="MeterLocation_Meter" Member="Meters" ThisKey="ID" OtherKey="MeterLocationID" Type="Meter" />
    </Type>
  </Table>
  <Table Name="dbo.MeasurementType" Member="MeasurementTypes">
    <Type Name="MeasurementType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="MeasurementType_Channel" Member="Channels" ThisKey="ID" OtherKey="MeasurementTypeID" Type="Channel" />
    </Type>
  </Table>
  <Table Name="dbo.Phase" Member="Phases">
    <Type Name="Phase">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Phase_Channel" Member="Channels" ThisKey="ID" OtherKey="PhaseID" Type="Channel" />
    </Type>
  </Table>
  <Table Name="dbo.SeriesType" Member="SeriesTypes">
    <Type Name="SeriesType">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="SeriesType_Series" Member="Series" ThisKey="ID" OtherKey="SeriesTypeID" Type="Series" />
    </Type>
  </Table>
  <Table Name="dbo.MeterLocationLine" Member="MeterLocationLines">
    <Type Name="MeterLocationLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeterLocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="MeterLocation_MeterLocationLine" Member="MeterLocation" ThisKey="MeterLocationID" OtherKey="ID" Type="MeterLocation" IsForeignKey="true" />
      <Association Name="Line_MeterLocationLine" Member="Line" ThisKey="LineID" OtherKey="ID" Type="Line" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeterFileGroup" Member="MeterFileGroups">
    <Type Name="MeterFileGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Meter_MeterFileGroup" Member="Meter" ThisKey="MeterID" OtherKey="ID" Type="Meter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Series" Member="Series">
    <Type Name="Series">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SeriesTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SourceIndexes" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="SeriesType_Series" Member="SeriesType" ThisKey="SeriesTypeID" OtherKey="ID" Type="SeriesType" IsForeignKey="true" />
      <Association Name="Channel_Series" Member="Channel" ThisKey="ChannelID" OtherKey="ID" Type="Channel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Channel" Member="Channels">
    <Type Name="Channel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasurementTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeasurementCharacteristicID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhaseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SamplesPerHour" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="PerUnitValue" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HarmonicGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Enabled" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Channel_Series" Member="Series" ThisKey="ID" OtherKey="ChannelID" Type="Series" />
      <Association Name="Channel_BreakerChannel" Member="BreakerChannels" ThisKey="ID" OtherKey="ChannelID" Type="BreakerChannel" />
      <Association Name="MeasurementType_Channel" Member="MeasurementType" ThisKey="MeasurementTypeID" OtherKey="ID" Type="MeasurementType" IsForeignKey="true" />
      <Association Name="Phase_Channel" Member="Phase" ThisKey="PhaseID" OtherKey="ID" Type="Phase" IsForeignKey="true" />
      <Association Name="MeasurementCharacteristic_Channel" Member="MeasurementCharacteristic" ThisKey="MeasurementCharacteristicID" OtherKey="ID" Type="MeasurementCharacteristic" IsForeignKey="true" />
      <Association Name="Line_Channel" Member="Line" ThisKey="LineID" OtherKey="ID" Type="Line" IsForeignKey="true" />
      <Association Name="Meter_Channel" Member="Meter" ThisKey="MeterID" OtherKey="ID" Type="Meter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MeasurementCharacteristic" Member="MeasurementCharacteristics">
    <Type Name="MeasurementCharacteristic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Display" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="MeasurementCharacteristic_Channel" Member="Channels" ThisKey="ID" OtherKey="MeasurementCharacteristicID" Type="Channel" />
    </Type>
  </Table>
  <Table Name="dbo.Line" Member="Lines">
    <Type Name="Line">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssetKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="VoltageKV" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ThermalRating" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Line_MeterLocationLine" Member="MeterLocationLines" ThisKey="ID" OtherKey="LineID" Type="MeterLocationLine" />
      <Association Name="Line_Channel" Member="Channels" ThisKey="ID" OtherKey="LineID" Type="Channel" />
      <Association Name="Line_MeterLine" Member="MeterLines" ThisKey="ID" OtherKey="LineID" Type="MeterLine" />
      <Association Name="Line_Structure" Member="Structures" ThisKey="ID" OtherKey="LineID" Type="Structure" />
      <Association Name="Line_FaultDetectionLogic" Member="FaultDetectionLogics" ThisKey="ID" OtherKey="LineID" Type="FaultDetectionLogic" />
    </Type>
  </Table>
  <Table Name="dbo.MeterLine" Member="MeterLines">
    <Type Name="MeterLine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MeterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LineName" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Line_MeterLine" Member="Line" ThisKey="LineID" OtherKey="ID" Type="Line" IsForeignKey="true" />
      <Association Name="Meter_MeterLine" Member="Meter" ThisKey="MeterID" OtherKey="ID" Type="Meter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Meter" Member="Meters">
    <Type Name="Meter">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssetKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MeterLocationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Alias" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Make" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Model" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="TimeZone" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Meter_MeterFileGroup" Member="MeterFileGroups" ThisKey="ID" OtherKey="MeterID" Type="MeterFileGroup" />
      <Association Name="Meter_Channel" Member="Channels" ThisKey="ID" OtherKey="MeterID" Type="Channel" />
      <Association Name="Meter_MeterLine" Member="MeterLines" ThisKey="ID" OtherKey="MeterID" Type="MeterLine" />
      <Association Name="Meter_GroupMeter" Member="GroupMeters" ThisKey="ID" OtherKey="MeterID" Type="GroupMeter" />
      <Association Name="MeterLocation_Meter" Member="MeterLocation" ThisKey="MeterLocationID" OtherKey="ID" Type="MeterLocation" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Structure" Member="Structures">
    <Type Name="Structure">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AssetKey" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Line_Structure" Member="Line" ThisKey="LineID" OtherKey="ID" Type="Line" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BreakerChannel" Member="BreakerChannels">
    <Type Name="BreakerChannel">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ChannelID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BreakerNumber" Type="System.String" DbType="VarChar(120) NOT NULL" CanBeNull="false" />
      <Association Name="Channel_BreakerChannel" Member="Channel" ThisKey="ChannelID" OtherKey="ID" Type="Channel" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GroupMeter" Member="GroupMeters">
    <Type Name="GroupMeter">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MeterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Meter_GroupMeter" Member="Meter" ThisKey="MeterID" OtherKey="ID" Type="Meter" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.FaultDetectionLogic" Member="FaultDetectionLogics">
    <Type Name="FaultDetectionLogic">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Expression" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="Line_FaultDetectionLogic" Member="Line" ThisKey="LineID" OtherKey="ID" Type="Line" IsForeignKey="true" />
    </Type>
  </Table>
</Database>